#!/bin/bash
set -e

# Script to update the list of building types from Wikidata
# Run periodically (e.g., monthly) to keep the list current

OUTPUT_FILE="src/services/building-types.ts"

echo "Fetching building types from Wikidata..."

# Get all building subtypes up to 5 levels deep
QUERY='
SELECT DISTINCT ?type WHERE {
  ?type wdt:P279+ wd:Q41176 .
  FILTER EXISTS {
    ?type wdt:P279?/wdt:P279?/wdt:P279?/wdt:P279?/wdt:P279? wd:Q41176 .
  }
}
ORDER BY ?type
'

# Fetch from Wikidata
curl -s -H "Accept: application/sparql-results+json" \
  --data-urlencode "query=$QUERY" \
  "https://query.wikidata.org/sparql" > /tmp/building_types.json

# Check if successful
COUNT=$(jq -r '.results.bindings | length' /tmp/building_types.json 2>/dev/null || echo "0")

if [ "$COUNT" -eq "0" ]; then
  echo "Error: No results from Wikidata. Check rate limiting or query syntax."
  exit 1
fi

echo "Found $COUNT building types (all subtypes up to 5 levels)"

# Generate TypeScript file
cat > "$OUTPUT_FILE" << 'HEADER'
/**
 * Building types for Wikidata SPARQL queries
 *
 * This list contains ALL building subtypes up to 5 levels deep
 * from Q41176 "building" (includes ~9000 types).
 *
 * Auto-generated by scripts/update-building-types.sh
 * Last updated: $(date -I)
 *
 * To update: run `bash scripts/update-building-types.sh`
 */

export const BUILDING_TYPES = [
  'Q41176', // building (root)
HEADER

# Extract Q-numbers and add to file
jq -r '.results.bindings[].type.value | sub("http://www.wikidata.org/entity/"; "")' \
  /tmp/building_types.json | \
  awk '{print "  '\''" $1 "'\'',"}' >> "$OUTPUT_FILE"

# Close array
cat >> "$OUTPUT_FILE" << 'FOOTER'
] as const;

/**
 * Generates SPARQL VALUES clause for building types
 */
export function buildingTypesValues(): string {
  return 'VALUES ?type { ' + BUILDING_TYPES.map(t => `wd:${t}`).join(' ') + ' }';
}
FOOTER

echo "✓ Generated $OUTPUT_FILE with $COUNT types"
echo ""
echo "Next steps:"
echo "1. Review the generated file"
echo "2. Update src/services/wikidata.ts to use buildingTypesValues()"
echo "3. Test query performance"
