#!/usr/bin/env python3
"""
Fetches all Wikidata building types (subclasses of Q41176) via iterative BFS,
avoiding the silent partial-result problem of transitive wdt:P279+ SPARQL queries.
"""

import json
import sys
import time
import urllib.parse
import urllib.request
from datetime import date
from pathlib import Path

SPARQL_ENDPOINT = "https://query.wikidata.org/sparql"
OUTPUT_FILE = Path(__file__).parent.parent / "src/services/building-types.ts"
BATCH_SIZE = 200  # max items per VALUES clause
HEADERS = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "Domus/1.0 (https://domus.genealogy.net; update-building-types)",
}


def sparql(query: str, retries: int = 4) -> list[str]:
    """Run a SPARQL query via POST and return Q-IDs from the first binding variable."""
    data = urllib.parse.urlencode({"query": query, "format": "json"}).encode()
    req = urllib.request.Request(
        SPARQL_ENDPOINT,
        data=data,
        headers={**HEADERS, "Content-Type": "application/x-www-form-urlencoded"},
    )
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                result = json.load(resp)
            bindings = result["results"]["bindings"]
            var = result["head"]["vars"][0]
            return [
                b[var]["value"].removeprefix("http://www.wikidata.org/entity/")
                for b in bindings
                if var in b
            ]
        except Exception as e:
            if attempt == retries - 1:
                raise
            wait = 2 ** attempt * 3
            print(f"  Retrying after {wait}s ({e})...")
            time.sleep(wait)
    return []


def fetch_children(parents: list[str]) -> list[str]:
    """Get direct P279 children of a batch of parent Q-IDs."""
    values = " ".join(f"wd:{q}" for q in parents)
    query = f"""
SELECT DISTINCT ?type WHERE {{
  ?type wdt:P279 ?parent .
  VALUES ?parent {{ {values} }}
}}"""
    return sparql(query)


def fetch_q811102_instances() -> list[str]:
    """Fetch explicit instances of Q811102 (type of building)."""
    return sparql("SELECT DISTINCT ?type WHERE { ?type wdt:P31 wd:Q811102 }")


def bfs_from(root: str) -> set[str]:
    """BFS over P279 hierarchy from root, one hop per iteration."""
    seen = {root}
    frontier = [root]
    iteration = 0
    while frontier:
        iteration += 1
        children: list[str] = []
        # Batch the VALUES clause to avoid URL length limits
        for i in range(0, len(frontier), BATCH_SIZE):
            batch = frontier[i : i + BATCH_SIZE]
            children.extend(fetch_children(batch))
            time.sleep(1)
        new = [q for q in children if q not in seen]
        print(f"  Iteration {iteration}: frontier={len(frontier)}, new={len(new)}")
        seen.update(new)
        frontier = new
    return seen


def write_ts(types: set[str]) -> None:
    sorted_types = sorted(types - {"Q41176"})
    lines = [
        "/**",
        " * Building types for Wikidata SPARQL queries",
        " *",
        " * Contains all Q-IDs that are either:",
        " * - subclasses (P279+) of Q41176 (building), or",
        " * - instances (P31) of Q811102 (type of building)",
        " *",
        " * Auto-generated by scripts/update-building-types.py",
        " * To update: run `python3 scripts/update-building-types.py`",
        " */",
        "",
        "export const BUILDING_TYPES = [",
        "  'Q41176', // building (root)",
    ]
    lines += [f"  '{q}'," for q in sorted_types]
    lines += [
        "] as const;",
        "",
        "export const BUILDING_TYPE_SET = new Set<string>(BUILDING_TYPES);",
        "",
    ]
    OUTPUT_FILE.write_text("\n".join(lines))


def main() -> None:
    print("BFS over P279 subclasses of Q41176 (building)...")
    building_types = bfs_from("Q41176")
    print(f"  Total subclasses: {len(building_types) - 1}")

    print("Fetching instances of Q811102 (type of building)...")
    extra = fetch_q811102_instances()
    print(f"  Found {len(extra)} instances")

    all_types = building_types | set(extra)
    print(f"\nTotal unique types: {len(all_types)}")

    write_ts(all_types)
    print(f"✓ Written to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
